version: 1
disable_existing_loggers: False
formatters:
  json:
    class: json_logger.JsonFormatter
handlers:
  default:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stderr


loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [default]
    propagate: false
root:
  level: DEBUG
  handlers: [default]
