openapi: 3.0.0
info:
  title: my-project
  version: '0.1'

x-yc-apigateway:
  service_account_id: ${API_SA_ID}

paths:
  /{proxy+}:
    x-yc-apigateway-any-method:
      parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: ${CONTAINER_ID}
        tag: $latest


components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: api_key # Always present in request
      x-yc-apigateway-authorizer:
        type: function
        function_id: ${FUNCTION_ID}
        tag: $latest
