openapi: 3.0.0
info:
  title: my-project
  version: '0.1'

x-yc-apigateway:
  service_account_id: ${API_SA_ID}
  cors:
    origin: '*'
    methods: '*'
    allowedHeaders: '*'

paths:
  /api/{proxy+}:
    x-yc-apigateway-any-method:
      parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: ${API_CONTAINER_ID}
        tag: $latest

  /api/auth/{proxy+}:
    x-yc-apigateway-any-method:
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: ${AUTH_CONTAINER_ID}
        tag: $latest


