name: Deploy to Server

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

env:
  IMAGE_TAG: cr.yandex/crp31fj9u7aj7h70jn5t/api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: build docker image

        run: |
          docker build -t $IMAGE_TAG:${{ github.sha }} -f project/Dockerfile .
          docker push $IMAGE_TAG:${{ github.sha }}


      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: sls-2
          folder-id: ${{secrets.FOLDER_ID}}
          revision-service-account-id: ${{secrets.SERVICE_ACCOUNT_ID}}
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/crp31fj9u7aj7h70jn5t/api:${{ github.sha }}
          revision-execution-timeout: 100


